### ISSUE TITLE
[v2] Project Routes

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-Backend#110]
The following project routes need to be added:
- [x] `/project/` (GET): Returns a list of all (approved) projects. (#114)
- [x]  `/project/add/` (POST): Registers a new project. (#112)
- [x] `/project/details/` (POST): Returns the details of a particular project. (project id provided in JSON body) (#114)
- [x] `/project/update/` (PUT): Update a particular project. (project id and details provided in the JSON body) (#115)
