### ISSUE TITLE
[v2] Stats Routes

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-Backend#116]
The following endpoints need to be added:
- [ ] `/stats/students` (GET): Returns a list of stats of all students. (#138)
- [ ] ~~`/stats/student/{username}` (GET, with login): Returns (detailed) stats of a particular student.~~ (Merge into #127)
- [ ] `/stats/projects` (GET): Returns a list of stats of all projects.  (#140)
- [ ] ~~`/stats/mentor/{username}` (GET, with login): Returns (detailed) stats of each project of a particular mentor.~~ (Merge into #127)
- [ ] `/stats/overall` (GET): Returns the overall KWoC stats. (#139)
