### ISSUE TITLE
[v2] Update Annotations for API Routes

### ISSUE THREAD

**Issue by YoganshSharma** [kossiitkgp/KWoC-Backend#150]
Refer the existing annotations and [this](https://github.com/swaggo/swag#declarative-comments-format)
- [x] /api/ GET (#176)
- [x] /oauth/ POST (#155)
- [x] /student/form/ POST #149
- [x] /student/bloglink/ POST #149 
- [x] /student/dashboard/ GET (#156)
- [x] /mentor/form/ POST (#176)
- [x] /mentor/all/ GET (#176)
- [x] /healthcheck/ GET (#156)
- [x] /healthcheck/ping/ GET #149
- [ ] /project/ POST
- [ ] /project/ GET
- [ ] /project/ PUT
- [ ] /project/{id} GET
- [ ] /stats/students/ GET
- [ ] /stats/overall/ GET
- [ ] /stats/projects/ GET
